const RoomActionTypes = {
  SET_CURRENT_ROOM : 'SET_CURRENT_ROOM',
  TOGGLE_CREATE_ROOM_HIDDEN:'TOGGLE_CREATE_ROOM_HIDDEN',
  TOGGLE_JOIN_ROOM_HIDDEN:'TOGGLE_JOIN_ROOM_HIDDEN',
  CLOSE_ALL_ROOM_POPUP:'CLOSE_ALL_ROOM_POPUP' 
}


export default RoomActionTypes;