const UserActionTypes = {
  SET_CURRENT_USER:'SET_CURRENT_USER',
  TOGGLE_SETTINGS_HIDDEN:'TOGGLE_SETTINGS_HIDDEN',
  TOGGLE_FIND_USER_HIDDEN:'TOGGLE_FIND_USER_HIDDEN',
  CLOSE_ALL_USER_POPUP:'CLOSE_ALL_USER_POPUP'
}

export default UserActionTypes;